# launch an EC2 in a default VPC in us-west 1 region , tag the EC2 with MY name "Cedric" 
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-060d3509162bcc386 # Amazon Linux 2 AMI (HVM), SSD Volume Type
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Cedric
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      CidrBlock: '10.0.0.0/24'
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: default-vpc
Outputs:
  InstanceID:
    Description: Instance ID of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
